name: ci

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        base: [debian, alpine]

    name: ${{ matrix.base }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          tags: |
            type=ref,event=tag,prefix=${{ matrix.base }}-
            type=match,pattern=.*,value=${{ matrix.base }}
          flavor: |
            latest=${{ matrix.base == 'alpine' }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.base }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
